# basic options
title: Vakantie juni 2021 - Friesland
author: Kees
description: Blog van de kampeervakantie van juni 2021

# URL to GitHub repo
baseurl: "/2021-06-friesland"
url: "https://prudento-nl.github.io"

# URL to images folder at GitHub repo LET OP het format van de link met de PUNT!
images: "https://prudento-nl.github.io/2021-06-friesland/images"

# Build settings
markdown: kramdown
theme: minima

minima:
  date_format: "%d-%m-%Y"
